### PR TITLE
Wrap response Arrays in JSONObject

### LINKED ISSUE #7: The library doesn't work on REST Endpoints that return JSONArray as response
The library doesn't work on REST Endpoints that return JSONArray as response.
EX: https://public-api.wordpress.com/rest/v1/plans/?pretty=true

The problem is here https://github.com/Automattic/android-wordpress-com-rest/blob/4b04a7fe3f3ad69b031eb51a6e134528add600aa/WordPressComRest/src/main/java/com/wordpress/rest/RestRequest.java#L111-L120
where it tries to parse the response document as JSONObject, instead it's a JSONArray, and a valid response.

As per chat convo we've decided to apply a quick patch, that wrap the response Array into a JSONObject.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #7 by catching the first ParseError, and try to parse the response as Array. Then wrap it in a JSONObject.

### CODE REVIEW

**Comment by maxme** [comment]
What about using `JSONTokener` and use `instanceOf` to check if the `nextvalue()` is a `JSONArray` or `JSONObject` instead of the try/catch?

**Comment by daniloercoli** [comment]
I didn't use JSONTokener because only 1 Endpoint returns an Array as response. It seems a bit redundant to check if it's an array or an object on every call. I can change it though.

**Comment by daniloercoli** [comment]
```

**Comment by maxme** [comment]
> I didn't use JSONTokener because only 1 Endpoint returns an Array as response. It seems a bit redundant to check if it's an array or an object on every call. I can change it though.

Ok, let's use the try/catch trick instead

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
